// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyyupvzawznwihojxiwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5eXVwdnphd3pud2lob2p4aXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MjIxODksImV4cCI6MjA2MjM5ODE4OX0.WJ5WreLN28ugxqp7e_Nn9JwoBHN7_sektntY6BkJ40Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);