
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxkelzoxxsixqfblnjwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4a2Vsem94eHNpeHFmYmxuandqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMDc1OTAsImV4cCI6MjA2NDU4MzU5MH0._tTLH87xgIT_bWH5z6XAOsd35HCCnhzpHofbqwbwRuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
